name: Test and Validate Code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository code
      uses: actions/checkout@v4

    - name: Run system check
      run: |
        echo "Starting automation..."
        node --version
        echo "Environment successfully verified!"
